
CREATE TABLE public.app_user (
	id serial4 NOT NULL,
	title varchar(15) NOT NULL DEFAULT ''::character varying,
	first_name varchar(32) NOT NULL DEFAULT ''::character varying,
	last_name varchar(32) NOT NULL DEFAULT ''::character varying,
	email varchar(256) NOT NULL DEFAULT ''::character varying,
	uniqid uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
	registered bool NOT NULL DEFAULT false,
	"password" varchar(128) NOT NULL DEFAULT ''::character varying,
	roles _text NULL DEFAULT '{user}'::text[],
	refresh_tokens TEXT[] DEFAULT ARRAY[]::TEXT[],
	status varchar(10) NOT NULL DEFAULT ''::character varying,
	phone_number varchar(20) NOT NULL DEFAULT ''::character varying,
	devices json NULL DEFAULT '{}'::json,
	created_on timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	modified_on timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	modified_by varchar(32) NOT NULL DEFAULT ''::character varying,
	deleted bool NOT NULL DEFAULT false,
	CONSTRAINT app_user_email_key UNIQUE (email),
	CONSTRAINT app_user_pkey PRIMARY KEY (id)
);

CREATE TABLE public.catalogue (
	id serial4 NOT NULL,
	title varchar(32) DEFAULT ''::character varying NOT NULL,
	category varchar(128) DEFAULT ''::character varying NOT NULL,
	description varchar(256) DEFAULT ''::character varying NOT NULL,
	slug varchar(256) DEFAULT ''::character varying NOT NULL,
	web_url varchar(512) DEFAULT ''::character varying NOT NULL,
	"content" text DEFAULT ''::text NOT NULL,
	image varchar(400) DEFAULT ''::character varying NOT NULL,
	average_rating numeric(3, 2) DEFAULT 0.00 NOT NULL,
	download_count int4 DEFAULT 0 NOT NULL,
	price numeric(10, 2) DEFAULT 0.00 NOT NULL,
	has_in_app_purchases bool DEFAULT false NOT NULL,
	"version" varchar(32) DEFAULT ''::character varying NOT NULL,
	platform varchar(128) DEFAULT ''::character varying NOT NULL,
	release_date date NULL,
	developer varchar(128) DEFAULT ''::character varying NOT NULL,
	supported_languages _text NULL,
	tags _text NULL,
	app_store_url varchar(512) DEFAULT ''::character varying NOT NULL,
	play_store_url varchar(512) DEFAULT ''::character varying NOT NULL,
	published bool DEFAULT false NOT NULL,
	published_on timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	created_on timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	modified_on timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	modified_by varchar(32) DEFAULT ''::character varying NOT NULL,
	deleted bool DEFAULT false NOT NULL,
	youtube_url varchar(512) DEFAULT ''::character varying NULL,
	CONSTRAINT catalogue_pkey PRIMARY KEY (id)
);

CREATE TABLE public.post (
    id serial4 PRIMARY KEY,
    title varchar(255) NOT NULL,
    slug varchar(255) UNIQUE NOT NULL,
    content text NOT NULL,
    author varchar(128) NOT NULL,
    excerpt varchar(512),
    image varchar(400),
    category varchar(128),
    tags _text,
    status varchar(32) DEFAULT 'draft',
    published_on timestamp DEFAULT CURRENT_TIMESTAMP,
    created_on timestamp DEFAULT CURRENT_TIMESTAMP,
    modified_on timestamp DEFAULT CURRENT_TIMESTAMP,
    modified_by varchar(32),
    deleted bool DEFAULT false NOT NULL
);

INSERT INTO public.app_user (title, first_name, last_name, email, uniqid, registered, "password", created_on, modified_on, modified_by, deleted, roles, status, phone_number) VALUES('', 'nosh', 'ghazanfar', 'nosherwan@gmail.com', 'a34b41cd-6727-4699-9074-32b352589bd8'::uuid, true, '$2a$10$lS8cxqsBcyjaF3s7tGA.3.PwRPCVwcc3usp1BvZQ8Uii1CU22GKgy', '2022-08-15 11:11:38.120', '2022-08-15 16:50:25.911', '', false, '{user,admin}', 'approved', '');
INSERT INTO public.app_user (title, first_name, last_name, email, uniqid, registered, "password", created_on, modified_on, modified_by, deleted, roles, status, phone_number) VALUES('', 'bruce', 'wayne', 'nosherwan+bw@gmail.com', '77f0995e-9be6-4a3c-bbfa-e678426dd033'::uuid, true, '$2a$10$APGekfn/dWxUtemHwwVGkOFuBFhdlLeG2h2TV2PssXa/jHMi0GKFG', '2022-08-15 18:39:09.960', '2022-08-15 18:39:09.966', '', false, '{user}', 'approved', '');
INSERT INTO public.app_user (title, first_name, last_name, email, uniqid, registered, "password", created_on, modified_on, modified_by, deleted, roles, status, phone_number) VALUES('', 'test', 'tester', 'nosherwan+t@gmail.com', '77f0995e-9be6-4a3c-bbfa-e678426dd033'::uuid, true, '$2a$10$APGekfn/dWxUtemHwwVGkOFuBFhdlLeG2h2TV2PssXa/jHMi0GKFG', '2022-08-15 18:39:09.960', '2022-08-15 18:39:09.966', '', false, '{user}', 'approved', '');

INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Headspace', 'Mindfulness', 'The mental health app for every moment. Popular guided meditation and mindfulness app', 'headspace', 'https://www.headspace.com', 'Headspace helps improve your sleep with sleep tools, relaxing music, sleepcasts, and more.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741581940/headspace-mobile-app-view_qceskg.webp', 4.80, 100000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{support,mindfulness,young,anxiety,wellbeing,study,meditation,work,for,people,online,health,and,depression,mental,youth}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/u2LFrsaBRXc?si=u9sMC9GBNgrc_fyY');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Calm', 'Mindfulness', 'Calm your mind. Change your life. Comprehensive meditation and sleep app', 'calm', 'https://www.calm.com', 'Mental health is hard. Getting support doesn''t need to be. Our app puts the tools to feel better in your back pocket, with personalized content to manage stress and anxiety, get better sleep, and feel more present in your life. Relax your mind, and wake up as the person you want to be.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741582267/calm-app-screenshots_v7a8qk.png', 4.80, 50000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{stress,mindfulness,relaxation,anxiety,stories,meditation,reduction,sleep,wellness,relief,music,mental}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/EXZ3didaDBM?si=XJNwnR0j7zMDB_qg');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Insight Timer', 'Mindfulness', 'Free app with an extensive library of guided meditations', 'insight-timer', 'https://insighttimer.com', 'With over 300,000 titles, we publish the largest ad-free library of guided meditations, music tracks and talks on earth.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741582958/insight-timer_yineka.png', 3.40, 5000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{mindfulness,anxiety,meditation,yoga,sleep,talks,music,breathwork,guided}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/nJGQDCEHEYA?si=Mwfw0WLN_ZDZS4pj');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Smiling Mind', 'Mindfulness', 'Free mindfulness app developed for all age groups', 'smiling-mind', 'https://www.smilingmind.com.au', 'Welcome to your versatile and practical mental fitness toolkit. Designed for minds of all ages and stages, the new Smiling Mind App helps you learn the skills that promote mental wellbeing and create the habits to thrive.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741852139/smiling-mind-app_hymzq4.png', 4.60, 9000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{act,mindfulness,flexible,learn,embrace,thinking,your,recharge,meditation,connections,fitness,practice,mindfully,purposefully,health,body,mental,grow,live}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/CKkMfY-8F-Q?si=IUMp49DBkP5tyW8R');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Happier', 'Mindfulness', 'Accessible meditation app aimed at beginners', 'meditate-happier', 'https://www.meditatehappier.com/', 'Discover a meditation app that evolves with you, offering a flexible and personalized approach to mindfulness. Get more out of meditation, so you can give more to every part of your life.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741852360/happier-meditation_jbrd5u.png', 4.70, 50000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{stress,personalized,mindfulness,anxiety,meditations,courses,meditation,reduction,sleep,wellness,relief,plans,mental,guided}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/6lxxU-5_epc?si=1gx3SlDlPB43tXBA');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Buddhify', 'Mindfulness', 'App offering on-the-go guided meditations', 'buddhify', 'https://www.buddhify.com', 'buddhify is the only meditation app designed to fit into a busy modern lifestyle. Known for its beauty and incredible value for money, it is loved and used around the world.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741853068/buddhify_kwictz.png', 4.70, 0, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{mindfulness,meditation,stress,sleep,calm,wellbeing,audio,guided,routines,practices,mobile,app,exercises,focus,emotions,anxiety,relaxation,kids,walking,work,breathing}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/B8TjIWPxwCU?si=7CtDNAKDiqaqRT-O');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Simple Habit', 'Mindfulness', 'Short sessions designed for busy lifestyles', 'simple-habit', 'https://www.simplehabit.com', 'Simple Habit is #1 app for your wellness & sleep recommended by top psychologists, therapists and mental health experts. Try Simple Habit for free today and join over 5 million people on this life-changing journey. Sleep better and be happier in your life, marriage, parenthood, work, and health.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741854091/simple-habit-app_dhziqp.png', 4.80, 1000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{mindfulness,meditation,sleep,stress,relief,wellness,motivation,relaxation,anxiety,depression,focus,calm,habit,coaching,experts,therapy,audio,guided}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/V9rMx-NjxRU?si=jYL9GFRGR08JuRsM');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Waking Up', 'Mindfulness', 'Philosophical and advanced meditation app', 'waking-up', 'https://wakingup.com', 'Meditation is more than just relieving stress, sleeping better, or improving your focus. While Waking Up can help you do all of that, it’s more like a whole new operating system for your mind. It can open the door to a deeper understanding of yourself and a new way of being in the world.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741854752/waking-up-app_sy23qq.png', 4.90, 1000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{mindfulness,meditation,consciousness,philosophy,science,mind,awareness,sam,harris,theory,practice,daily,lessons,conversations,sleep,stress,anxiety,rationality,well-being}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/DH8hMT17AiU?si=xcveWvGzGPVUHXBc');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Medito', 'Mindfulness', 'Meditation can positively transform people''s lives and no one should have to pay for it.', 'medito', 'https://meditofoundation.org/', 'Meditation and mindfulness can greatly improve mental wellbeing and can have a transformative effect on all of us as individuals and on society as a whole.

Help us improve mental wellbeing by ensuring mindfulness and meditation resources are available to everyone, for free.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741862279/medito-app_yfddza.png', 4.90, 1000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{meditation,mindfulness,mental,health,well-being,stress,anxiety,sleep,resources,free,support,practices}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/HEPNPCh97kA?si=eTLv1l3nWyrvrP2B');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Meditopia', 'Mindfulness', 'Guided meditations focusing on overall well‐being', 'meditopia', 'https://meditopia.com', 'Feel happier and improve your emotional health with our mindfulness meditation program. Reduce stress, anxiety, and sleep better.

You’re in the right place to reduce both your stress and anxiety levels and sleep better.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741857491/meditopia-app_upicpj.png', 4.90, 10000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{meditation,mindfulness,sleep,stress,anxiety,happiness,relationships,focus,motivation,body,mind,wellbeing,audio,guided,stories,nature,sounds,breath,personalized}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/Zo09WSpkITU?si=kQd_rGARxEKF-jjW');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Beyond Now', 'Mindfulness', 'If you or someone close to you is considering suicide, a safety plan can be a reminder of the reasons to live and ways to stay safe.', 'beyond-now', 'https://www.lifeline.org.au/', 'The Beyond Now suicide safety planning app assists you to create your own suicide safety plan; a plan to keep you safe when experiencing suicidal thoughts. Using the app, you can list ideas and contacts to stay safe, including warning signs, coping strategies, reasons for living, and ways to make your environment safe.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741934207/beyond-now-app_qq1ncm.png', 4.00, 50000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{suicide,safety,plan,mental,health,coping,crisis,distress,thoughts,app,support,warning,signs,strategies,help,emergency,contacts}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/diBCnbiBYJ4?si=vjc7-FV5NKCR7gQG');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Breethe', 'Mindfulness', 'Meditation, hypnotherapy, stories, music, sounds - wellness solutions that work. ', 'breethe', 'https://breethe.com/', 'Breethe gives you more ways to tune out, wind down, and drop off, including meditations, hypnotherapy, stories, music, and sounds.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741857886/breethe-app_qhvtkl.png', 4.70, 1000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{meditation,sleep,hypnotherapy,music,sounds,stories,wellness,self-care,anxiety,stress,mindfulness,relaxation,coaching}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/ttWS5eMtuhg?si=J_GeB3MeW4SlZuud');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Finch', 'Mindfulness', 'Your new self care best friend', 'finch', 'https://finchcare.com/', 'Meet your new self-care best friend! Finch is a self-care pet app that helps you feel prepared and positive, one day at a time. Take care of your pet by taking care of yourself! Choose from a wide variety of self-care exercises personalized for you.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741949516/finch-self-care-pet-app_wk4sxg.png', 4.90, 5000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{self-care,mental,health,daily,check-in,moods,goals,habits,journaling,breathing,exercises,reminders,personalized,support,wellbeing,routines}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/7opbdtb9XgQ?si=jFFOdPcwOy6Bn3R2');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('The Mindfulness App', 'Mindfulness', 'App offering customizable guided and silent sessions', 'the-mindfulness-app', 'https://themindfulnessapp.com', 'Feeling overwhelmed or stressed in your everyday life? Want to feel more balanced and more joyful?

Enjoy a more restful sleep, stress less, and reduce your anxiety together with The Mindfulness App. With over 350 guided meditations and courses from experts around the world, we have options for every mood, time of the day, and for everyone from beginners to experienced.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741858206/the-mindfullness-app_eih1rf.png', 4.80, 1000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{mindfulness,meditation,sleep,stress,health,guided,courses,experts,topics,stories,reminders,personalized,focus,anxiety}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/kXa0D88lDKQ?si=nYRJQragyWr1kALB');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Oxford MBCT', 'Mindfulness', 'Free app based on Mindfulness-Based Cognitive Therapy', 'oxford-mbct', 'https://oxfordmindfulness.org', 'The new Oxford Mindfulness app has been designed for you to develop and maintain your mindfulness practice for your mental health and well-being. It offers a library of mindfulness meditations, live sessions, self-paced courses, resources and materials', 'https://res.cloudinary.com/nosherwan/image/upload/v1741858664/oxford-mindfulness-app_heudqn.png', 4.30, 1000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{mindfulness,mbct,therapy,training,courses,research,depression,mental,health,stress,wellbeing,cognitive,behavioral,oxford,university,teachers,practice,program}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, '');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Mind Valley', 'Mindfulness', 'Be part of the world’s most powerful life transformation platform', 'mindvalley', 'https://www.mindvalley.com/', 'Step into your greatness with Mindvalley, a transformational learning platform where you can learn, connect, and share insights with like-minded individuals who strive for personal growth. Immerse yourself in lessons, meditations and lifehacks from world-class trainers like Vishen, Lisa Nichols, Marisa Peer, Paul McKenna, Sadhguru, and more. Dive into talks with entrepreneurs, tools by expert coaches and teachings from thought leaders from around the world.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741859218/mindvalley-app_rte82z.png', 4.80, 1000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{personal,growth,transformation,learning,online,courses,meditation,mind,body,soul,career,relationships,entrepreneurship,coaching,skills,motivation,focus,memory,health,wellbeing,spirituality}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/BSQsVlNa_TA?si=_KvsGH1SWkTUrHN6');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Balance', 'Mindfulness', 'Meditation app focusing on habit formation', 'balance', 'https://www.balanceapp.com', 'Balance is your personal meditation coach. Each day, you’ll answer questions about your meditation experience, goals, and preferences. Using an audio library of thousands of files, Balance assembles a daily meditation that''s perfect for you. The more you share over time, the more personalized and effective your meditations become.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741859809/balance-app_xx6uj3.png', 4.80, 1000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{meditation,personalized,sleep,stress,anxiety,wellbeing,mindfulness,audio,guided,programs,daily,questions,moods,goals,library,techniques}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/ujJXT02iNsU?si=C7DuPU-X0FOfF6wH');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Kinder World', 'Mindfulness', 'Welcome to your daily dose of kindness Cultivate your calm in just a few minutes each day - for free', 'kinder-world', 'https://www.playkinderworld.com/', 'Kinder World is a game about finding peace in everyday life. It''s a cozy wellbeing game with a relaxing atmosphere, designed for quick stress release in just two minutes a session, with gentle evidence-based activities as you raise unique houseplants.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741952292/kinder-world-app_wgjzbh.png', 4.70, 1000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{self-care,wellbeing,cozy,game,plants,emotional,stress,anxiety,mindfulness,gratitude,breathing,emotions,community,relaxation,decoration,personalization}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/tQLnkWdemW4?si=n23kvWQW6uubDD9a');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Focus@Will', 'Mindfulness', 'Focus@Will: Brain Music To Increase Your Focus', 'focus-at-will', 'https://www.focusatwill.com/', '

Customize for your specific brain type! Take the quiz to select the channel, select background images, session start sound and timer length...and BOOM get productive.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741952993/focus_will-app_ho4lmr.png', 4.20, 100000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{focus,music,productivity,concentration,attention,adhd,study,work,science,neuroscience,background,audio,streaming,deep,task,sessions}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://www.youtube.com/live/_U3heJPJFC0?si=VSjOF2RltLhR0Kdk');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Aura', 'Mindfulness', 'Personalized meditation with gratitude journaling', 'aura', 'https://www.aurahealth.io', 'Find peace every day with Aura, the Best of Apple award winner.

Transform your wellbeing & sleep with the world''s most personalized, all-in-one app for mental wellness.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741860425/aura-app_jum0xq.png', 4.70, 1000000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{meditation,mindfulness,sleep,stories,coaching,music,wellness,anxiety,stress,personalized,ai,mood,tracker,gratitude,breathwork,therapy,self-care}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/iZvaWmMAKj0?si=QyCJwlfUO7QMnI0I');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Inflow', 'Mindfulness', 'Let''s take control of your ADHD', 'inflow', 'https://www.getinflow.io/', 'Inflow is the #1 science-based app to help you manage your ADHD. Created by ADHD clinicians and psychologists, our dedicated support system helps you understand your neurodivergent brain, build lifelong skills, and get things done.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741953836/inflow-app_xmfytz.png', 4.30, 100000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{adhd,manage,focus,organization,procrastination,attention,hyperactivity,anxiety,routine,schedule,impulsivity,depression,medication,treatment,mindfulness,nutrition,cbt,skills,productivity,emotional,regulation}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/waI6IPB8hbU?si=KueTCY_sJhjq1pAa');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Soaak', 'Mindfulness', 'App using sound frequencies and guided sessions for sleep', 'soaak', 'https://www.soaak.com', 'Discover the Healing Power of Sound Frequencies

Enhance Your Wellness Journey with Clinically Curated Sound Frequencies: Introducing AI Integration, Wearable Connectivity, Dual Audio, and more!', 'https://res.cloudinary.com/nosherwan/image/upload/v1741860599/soak-app_mlxpnp.png', 4.60, 10000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{sound,frequencies,technology,mental,health,emotional,cognitive,function,sleep,stress,anxiety,focus,performance,energy,mood,wellbeing,audio,binaural,beats,isochronic,tones,neuroscience}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/GLaesJMNvkQ?si=tNKsgbu25g45ET2D');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Activations', 'Mindfulness', 'App blending motivational activations with meditation', 'activations', 'https://www.activations.com', 'Unlike traditional meditation which calms you, Activations are motivational, science-backed audio experiences designed to help you manifest a better life effortlessly. Feel the shift instantly as you evolve into your wealthiest, healthiest, and happiest self. Whether you’re walking, getting ready, or winding down, these transformative audios fit seamlessly into your busy life – so you’ll actually stick to using it.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741861066/activations-app_srjkfg.png', 4.80, 10000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{meditation,mindfulness,energy,healing,spiritual,growth,consciousness,transformation,guided,practices,rituals,sound,frequencies,breathwork,movement,self-care,wellbeing,personal,development}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/9awdczcWgKM?si=usxfohIBmgD5uKMi');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Breathwrk', 'Mindfulness', 'App focused on teaching breathing techniques', 'breathwrk', 'https://www.breathwrk.com', 'Breathwrk is #1 breathing app for Sleep, Stress, Focus, and Energy. Breathwrk is a simple yet powerful way to improve your mental and physical wellbeing in just seconds with neuroscience based breathing exercises. Join the millions breathing with Breathwrk across the world today!', 'https://res.cloudinary.com/nosherwan/image/upload/v1741861418/breathwrk-app_mfshpb.png', 4.80, 500000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{breathwork,breathing,exercises,calm,focus,stamina,sleep,health,performance,classes,guided,science,haptics,music,relaxation,stress,anxiety,energy}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/uudpQo9yknk?si=n828IW_yTdYak-01');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Clearful', 'Mindfulness', 'Be a more thoughtful, resilient, and happier you with daily journaling
', 'clearful', 'https://clearful.com/', 'We''re Clearful, the award-winning, modern journaling app packed with self-growth guided journals, AI-powered insights, beautiful design & top-tier customer support.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741954330/clearful-app_ygraey.png', 4.70, 5000, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{journaling,mindfulness,gratitude,reflection,mood,self-awareness,mental,wellbeing,emotions,prompts,habits,daily,guided,insights,personal,growth}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/lyumoNOCCwY?si=VY2JRuSPYAPjyBxg');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Simply Being Guided Meditation', 'Mindfulness', 'Customizable guided meditation app simply being', 'simply-being-guided-meditation', 'https://meditationoasis.com', '', '', 0.00, 0, 0.00, true, '', 'iOS, Android', NULL, '', NULL, '{meditation,guided}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', true, '');
INSERT INTO public.catalogue (title, category, description, slug, web_url, "content", image, average_rating, download_count, price, has_in_app_purchases, "version", platform, release_date, developer, supported_languages, tags, app_store_url, play_store_url, published, published_on, created_on, modified_on, modified_by, deleted, youtube_url) VALUES('Sleepiest', 'Mindfulness', 'Here to help you sleep better tonight', 'sleepiest', 'https://www.sleepiest.com/', 'Get the restful night of sleep you deserve, with Sleepiest’s award-winning bedtime stories, sleep sounds, meditations and sleep tracking.', 'https://res.cloudinary.com/nosherwan/image/upload/v1741861757/sleepiest-app_klw40w.png', 4.60, 5000, 0.00, true, '', 'iOS', NULL, '', '{}', '{sleep,stories,sounds,meditations,music,relaxation,bedtime,kids,calming,ambient,nature,white,noise,hypnosis,mindfulness,anxiety,stress}', '', '', true, '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '2025-03-10 14:36:38.624', '', false, 'https://youtu.be/fMcqPumUBJM?si=VP_xr3-Ro666kwah');
